### PR TITLE
Remove sys-iodbc

### PR DESCRIPTION
**Pull request by detule**
Hi @s-u :

Following up on the discussion in https://github.com/R-macos/recipes/issues/41.

This closes the issue.

Thanks!

### CODE REVIEW

**Comment by detule** [comment]
ping @s-u  :
Let me know if there is something I can do to move this forward.

Thank you!

**Comment by detule** [comment]
ping @s-u 

Apologies for being a squeaky wheel, but trying to figure out what it would take to get something like this in.

Cheers

**Comment by s-u** [comment]
I thought this was fixed in the last update round of the libraries where sys-odbc was excluded, if not can you tell me which build seems to have problems?

**Comment by detule** [comment]
Hey Simon:

Just so we are on the same page - not sure about *`sys-odbc`*; the contention is between the `sys-iodbc` and `unixodbc` recipes.  As best as I can tell they are still part of the build / am I missing something?

Our users starting reporting the issue with [R] 4.3.1 ( and `odbc` 1.3.5 ).

**Comment by s-u** [comment]
Please see above - include full error and the build.

**Comment by detule** [comment]
Simon thanks:

Not sure if you remember but we discussed this in https://github.com/R-macos/recipes/issues/41 ( where you agreed this is a problem ).

In particular, there is no error.  The issue at hand is that both `iodbc` and `unixodbc` provide a slightly different version of the generic `odbc` headers, and somewhat randomly the `iodbc` version clobbers over the `unixodbc` headers ( rather than, for example, the other way around ).

This causes an issue for `package:odbc` since during the build process we check for the existence of `unixodbc`, find it, and expect to be able to use it.  The problems are subtle - again no error, but for example, the two headers define a different storage size for wide characters which in turn can result in query results with characters missing, etc.

Beyond that not sure what kind of error report I can provide - but happy to do it, let me know.

**Comment by s-u** [comment]
As I said above I thought I fixed that so my question was if you are still getting an error, I’d need to know which build in case I missed one of them.

**Comment by detule** [comment]
Hi @s-u :

Thanks, and apologies for the miscommunication.
* Still seeing the error.
* Installed the package with `install.packages("odbc", type="mac.binary", contriburl="https://cran.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3")`
```
> dbGetQuery(conn, "SELECT * FROM ##og_temp")
  id name
1  1 aceg
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin23.0.0 (64-bit)
Running under: macOS Sonoma 14.0

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.24/lib/libopenblasp-r0.3.24.dylib
LAPACK: /usr/local/Cellar/r/4.3.2/lib/R/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] odbc_1.3.5

loaded via a namespace (and not attached):
 [1] bit_4.0.5       compiler_4.3.2  cli_3.6.1       hms_1.1.3
 [5] DBI_1.1.3       Rcpp_1.0.10     bit64_4.0.5     vctrs_0.6.2
 [9] blob_1.2.4      lifecycle_1.0.3 pkgconfig_2.0.3 rlang_1.1.1
```
Please let me know if you need additional info.  Thanks.

**Comment by s-u** [comment]
a) This is not CRAN is the session R so please ask Homebrew for support 
b) I don’t see any error so I’ll close this as not replicable since the PR apparently doesn’t help, and if you think there is a problem, please file a proper issue with necessary details such reproducible example using only CRAN binaries, exact statement of what is expected vs observed

**Pull request closed without merging**
