### PR TITLE
Update the protobuf recipe

### PR DESCRIPTION
**Pull request by coatless**
This should update the existing `protobuf` as a library for CRAN builds. 

We're assuming the CRAN build system has `autoconf`, `automake`, and `libtool` available.

/ cc @eddelbuettel

### CODE REVIEW

**Comment by coatless** [comment]
@s-u Anyway we could get this merged and built on CRAN? @eddelbuettel would like to release a new version of `RProtobuf` that supports macOS.

**Comment by eddelbuettel** [comment]
Actually I don't -- I'd simply prefer for the _existing_ package to build.  

Several of my packages never built on that esteemed OS, and @s-u did take to kindly to my suggestion of allowing me to disable builds there.

But I, as a maintainer, now get punished by CRAN for `ERROR` (as packages progress more slowly).  Yet `ERROR` is all I can get on macOS as soon as happen to deploy a non-standard library.  

It really is not ideal.  @coatless is kindly offering to build some libraries but we are running into "issues".

**Comment by coatless** [comment]
@s-u Any chance this could get merged? Soon (TM)?

**Comment by s-u** [comment]
Thanks, committed, tested, deployed.

However, there is a bug in `RProtoBuf` which prevents it from building anyway -- it uses the wrong compiler in `configure`. It has to pick up `CXX` and `CC` from R (which is `clang`), but the `configure` defaults to GCC for tests instead which won't work here so it fails. To be precise, you need probably something like
```
: ${CC=`${R_HOME}/bin/R CMD config CC`}
: ${CXX=`${R_HOME}/bin/R CMD config CXX`}
```
in `configure` before running any tests.

**Comment by eddelbuettel** [comment]
> However, there is a bug in RProtoBuf which prevents it from building anyway

Will fix.  Same idiom is used in other places, and Kurt usually reminds me to do it everywhere. Surprised it slipped here for so long.

**Comment by s-u** [comment]
Thanks. That may have been the issue before, since we did have protobuf 2.6.1 which should have been compatible.
Also I can set an override of `CC`/`CXX` for RProtoBuf in the meantime if it helps - I don't know when you get to push the new version.

**Comment by eddelbuettel** [comment]
Within days, possibly tomorrow.  

But please do it anyway.  Better to disentangle dependencies on any critical path.

**Comment by eddelbuettel** [comment]
@s-u  Can you, by chance, try the version [in the GH repo](https://github.com/eddelbuettel/rprotobuf) ?

That change was made in July, a good two weeks after the most recent release:
https://github.com/eddelbuettel/rprotobuf/blob/a181677d3cabb66d3fd536f480ac8ac68ba7b981/configure.ac#L15-L21

**Comment by eddelbuettel** [comment]
@s-u:  Is there something you can do about this one, please?
https://www.r-project.org/nosvn/R.check/r-oldrel-osx-x86_64/RProtoBuf-00check.html

**Pull request closed without merging**
