### PR TITLE
Create hwloc

### PR DESCRIPTION
**Pull request by theAeon**
Unsure if you want cairo/libxml linking as the idea (at least for my purposes) is to do a minimal build. This library is never interfaced with by the end user (again, at least for my purposes).

### CODE REVIEW

**Comment by s-u** [comment]
Thanks. Do you have a test-case? I.e., is there an R package that needs it?

PS: Is `automake` really needed? I'd think it is only needed for builds from the repo but not for releases, right?

**Comment by theAeon** [comment]
I'm currently using it to get cache size for chunking in https://github.com/welch-lab/RcppPlanc. Its not on CRAN yet due to difficulties reproducing a crash on win-builder but it will be.

If I'm remembering right, the reason I included automake in the requires is that the patch file removes most of the subdirs from makefile.am.

**Comment by s-u** [comment]
This is now accepted with a newer version

**Comment by s-u** [comment]
Thanks!

**Pull request closed without merging**
