### PR TITLE
add GMP C++ bindings

### PR DESCRIPTION
**Pull request by jeffreyhanson**
Thank you again for developing this repository!

I'm submitting this PR to (hopefully) add C++ bindings for the GMP library. Specifically, this PR updates the GMP recipe (i.e the `recipes/gmp` file) to add a compilation flag that will enable these bindings (i.e. `--enable-cxx`). For more information on this compilation flag, please see the [Build Options section of the GMP Manual](https://gmplib.org/manual/Build-Options) (specifically  "C++ Support, --enable-cxx" subsection).

To help verify that this PR works, I have created some additional branches and used GitHub Actions to verify that (1) the current GMP recipe does not provide these bindings (please see this [branch](https://github.com/jeffreyhanson/recipes/tree/gmpxx-fail) and [GitHub Actions results](https://github.com/jeffreyhanson/recipes/actions/runs/901490215)), (2) the updated recipe in this PR does provide these bindings (please see this [branch](https://github.com/jeffreyhanson/recipes/tree/gmpxx-success) and [GitHub Actions results](https://github.com/jeffreyhanson/recipes/actions/runs/901514964)), and (3) an R package which requires these C++ bindings can be built from source using the updated recipe file (please see this [branch](https://github.com/jeffreyhanson/recipes/tree/gmpxx-pkg-test) and [GitHub Actions results](https://github.com/jeffreyhanson/recipes/actions/runs/910396967)).

What do you think? Please let me know if there's anything I can do to improve this PR? Is there any additional information I can provide that would help you with assessing this PR (e.g. links to specific commits or GMP documentation)? Are there any additional changes I can make to the recipe to impove this PR? Or are there additional tests/checks I can run to help verify that this PR works as intended?

### CODE REVIEW

**Comment by s-u** [comment]
@jeffreyhanson thank you for your extensive testing! It sounds like good idea.

However, the patch should be probably a lot shorter since the setting is not arch-specfic so I'd simply add

```
Configure: --enable-cxx
```

I can either just do it myself or if you want to adjust your branch that's fine, too - just let me know what you prefer.

**Comment by jeffreyhanson** [comment]
Thanks for getting back so quickly! I'm happy to update the PR with the change (I don't want to waste your time with stuff that I can do for you). Would also you like me to re-run the tests with the updated recipe file too?

**Comment by s-u** [comment]
Since you already did all the work to setup the tests I'd say run the package test just to confirm that the result is identical. Thanks.

**Comment by jeffreyhanson** [comment]
I'm sorry, I tried to make the change and squash it so that I don't pollute the repository's history. But it seems like I only made things worse. If you don't mind, could I please close this PR and make a new PR with a new branch that just has a single commit with the `Configure: --enable-cxx` update?

**Comment by s-u** [comment]
You can just force-push to your current branch for this PR (I think) - assuming you did squash and rebase. But if you desire, you can create a new one, that's fine. (And sorry, I just added a documentation file to the repo - I forgot this will add an extra thing to worry about for you).

**Comment by jeffreyhanson** [comment]
Ok, I'll just make a new PR with a new branch. No worries - thanks for the heads up.

**Pull request closed without merging**
